### ISSUE TITLE
Apply the logging labels "ecosystem", "package" and "version" across all logging during an analysis run.

### ISSUE THREAD

**Issue by calebbrown** [ossf/package-analysis#185]
This will make it easier to filter logs in GCloud based on what is happening.

We likely need to refactor the logging to support this and may eventually need to pass a "logger" between various components.

**Comment by calebbrown** [comment]
Other related thoughts:

- as well as logging `ecosystem`, `package` and `version` we should also log `message id` across all logs. A pubsub message is useful as a context ID across the life of an individual analysis request.

**Comment by calebbrown** [comment]
Note: this is now being implemented by using `log/slog` in Go v1.21 and passing the vars in a Context.

**Comment by maxfisher-g** [comment]
@calebbrown can this be closed now?

**Comment by calebbrown** [comment]
Yes!
