### ISSUE TITLE
Sandbox failed (error starting container: exit status 125)

### ISSUE THREAD

**Issue by tbiens** [ossf/package-analysis#271]
Hello, I saw the blog post about this project. I'm excited to give it a try. Completely fresh ubuntu 22 lts server install vm. Docker.io is installed and functioning. golang and libpcap-dev installed. 

$ mkdir /tmp/results
$ docker run --privileged -ti \
    -v /tmp/results:/results \
    gcr.io/ossf-malware-analysis/analysis analyze \
    -package Django -ecosystem pypi \
    -upload file:///results/

https://imgur.com/a/Y578M0W

running with sudo vs root doesn't seem to make any significant difference. Thanks for the help!

**Comment by sycophantic** [comment]
I have the same issue with Ubuntu 20.04 and Docker version 20.10.14, build a224086.

**Comment by calebbrown** [comment]
Thanks for the report and the error message. I'll take a look.

**Comment by calebbrown** [comment]
The issue is that running a container inside a container requires the right filesystem.

**Comment by calebbrown** [comment]
I got it running by adding: `-v /var/lib/containers:/var/lib/containers` to map the location Podman stores it's containers to a filesystem outside of the Docker overlayfs.

Internet searches also suggest changing Docker's storage filesystem can also work around the issue.

I will update the docs.

**Comment by calebbrown** [comment]
Can you please try again with the updated command.

Feel free to re-open this issue if it doesn't work.

**Comment by tbiens** [comment]
I gave it a try adding var lib containers. No change in result.

**Comment by calebbrown** [comment]
I suspect the issue may be GVisor currently doesn't support cgroups v2 and has to use v1 instead (see: https://github.com/google/gvisor/issues/3481)

This is set during boot.

I'm not sure what boot loader your Linux system uses, but for Grub you can do this:

```
$ echo 'GRUB_CMDLINE_LINUX+=" systemd.unified_cgroup_hierarchy=0"' | sudo tee /etc/default/grub.d/cgroup.cfg
$ sudo update-grub
$ sudo reboot
```

**Comment by calebbrown** [comment]
I'll also check if a more recent version of GVisor is available

**Comment by tbiens** [comment]
I am not familiar with gvisor or cgroups. update-grub doesn't like that line. 

I installed Ubuntu 22.04 LTS Server:
apt install golang libpcap-dev docker.io
systemctl start docker
systemctl enable docker

Then heading right into the command that fails.

**Comment by calebbrown** [comment]
Please try again! I've updated the GVisor version and refreshed the container images.

You might need to rm the analysis image from docker to get the new one (or add `:latest` to it)

**Comment by tbiens** [comment]
Did a docker system prune -a 

No improvement. 

![image](https://user-images.githubusercontent.com/44678417/166947523-accc654e-7435-4ed0-b495-f42b26922e95.png)

**Comment by oliverchang** [comment]
Thanks for your patience @tbiens. I can reproduce this with cgroups v2 enabled. We'll take a closer look at this next week and hopefully resolve this.

**Comment by tbiens** [comment]
No problem, have a great weekend!

**Comment by oliverchang** [comment]
@tbiens I've managed to get this working locally with https://github.com/ossf/package-analysis/pull/276.

Could you please try this? (Just add `--cgroupns=host` to your `docker run` command).

**Comment by tbiens** [comment]
That did the job, output is scrolling well. 

Great job Oliver!
