### ISSUE TITLE
Improve new-starter ergonomics

### ISSUE THREAD

**Issue by calebbrown** [ossf/package-analysis#284]
It would be great if new comers to the project had a super smooth experience using the repo.

Operations that should be simple:

1. building the images locally
2. running the one-shot analysis for a given ecosystem, package and version
3. passing a tarball/zip into the one-shot analysis
4. running unit tests

To keep it simple the number of new/additional dependencies should be kept small (e.g. only need Docker and `make`)

**Comment by maxfisher-g** [comment]
Some remaining task: add a CONTRIBUTING.md file

**Comment by maxfisher-g** [comment]
Points 2 and 3 are substantially addressed by #359 and #391, but more improvements are possible. Some remaining tasks:

1. Add a CONTRIBUTING.md file
2. Create Makefile with things that you need to run to do development (dev tasks/tools like building, tests, copying built images into podman location)

**Comment by maxfisher-g** [comment]
The tasks above will be addressed in #399 and #400 respectively
