### ISSUE TITLE
GitHub Actions job runs probably aren't needed for Readme updates

### ISSUE THREAD

**Issue by case** [ossf/package-analysis#294]
I noticed GitHub Actions' `Checks: 12` in PR #287, which probably aren't necessary for things like Readme updates? (Build, test, scan, etc). Screenshot:

<img width="792" alt="Screen Shot 2022-06-02 at 11 12 25" src="https://user-images.githubusercontent.com/20105/171699090-069cb7d2-c484-4c61-8fe3-6403178125e9.png">

It looks like the current workflows all use a variant of:

```
on:
  pull_request:
```

…which triggers them to run for every pull request.

The relevant [GitHub Actions docs are here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) -- for example:

```
paths-ignore:
      - 'docs/**'
```

I'd be happy to draft up a PR for you, if you'd like? e.g. something like, "don't run when `.md` files are updated" for starters.

**Comment by calebbrown** [comment]
That's a fair point.

Certainly happy for you to submit a PR along these lines.

Ignoring `.md` files is certainly a good starting place.
