### ISSUE TITLE
Hook up crates feed via cargo

### ISSUE THREAD

**Issue by tom--pollard** [ossf/package-analysis#33]
Targeting a rust:minimal container for cargo builds of the given package tarballs for example

**Comment by tom--pollard** [comment]
The crates api exposes `https://crates.io/api/v1/crates/$package_name/$package_version/download` (values of which exist on the Package{} structs) which provides the given source tarball. This could then be extracted and installed with `cargo build` and during the analysis phase under falco

**Comment by calebbrown** [comment]
This is done.

#551 is logged to add import support.
