### ISSUE TITLE
Key storage methods deprecated

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/package-analysis#335]
During building the analysis image, there are some warnings in the build output

`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))`

`W: https://storage.googleapis.com/gvisor/releases/dists/20220425/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

**Comment by calebbrown** [comment]
https://stackoverflow.com/questions/68992799/warning-apt-key-is-deprecated-manage-keyring-files-in-trusted-gpg-d-instead has some good docs.
