### ISSUE TITLE
documentation-only changes can't be merged

### ISSUE THREAD

**Issue by oliverchang** [ossf/package-analysis#342]
We require that "Build" and "build_docker" actions pass before PRs are merged.

However, these actions ignore .md only PRs so they are never run on such PRs (https://github.com/ossf/package-analysis/blob/7279e199ea256d89a5a75b210dff16d0d781e5f4/.github/workflows/build.yml#L6). This means no .md-only changes can be merged.

**Comment by maxfisher-g** [comment]
The 'Build docker' action is also triggered on a push, which also is set to ignore .md files. Does this exclusion need to be removed too?

https://github.com/ossf/package-analysis/blob/7279e199ea256d89a5a75b210dff16d0d781e5f4/.github/workflows/build-images.yml#L9

**Comment by oliverchang** [comment]
> The 'Build docker' action is also triggered on a push, which also is set to ignore .md files. Does this exclusion need to be removed too?
> 
> https://github.com/ossf/package-analysis/blob/7279e199ea256d89a5a75b210dff16d0d781e5f4/.github/workflows/build-images.yml#L9

I think that's fine to keep. The pull_request ones are the problematic ones because those are blocked on those checks passing.
