### ISSUE TITLE
Make it impossible to mess up the schema.json

### ISSUE THREAD

**Issue by calebbrown** [ossf/package-analysis#357]
The schema.json repeats the "import" and "install" sections, which means you have to remember to update both sections. And can cause issues like: #356. If only one section is updated the other will stop being imported.

Here are a couple of ideas:

1. make "phase" a field in the schema, and remove the duplication (my preference, but old data can no longer be imported)
2. add a check that is executed by a GitHub action that validates the JSON.

**Comment by maxfisher-g** [comment]
At the very least, having a README for the schema.json where you can see the schema at a glance and make notes about this kind of stuff would make it "less possible" to mess it up.

**Comment by maxfisher-g** [comment]
Subsumed under #960
