### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/package-analysis#399]
We should have a CONTRIBUTING.md file that describes how to set things up for new contributors to the project. 
Example: https://github.com/ossf/criticality_score/blob/main/CONTRIBUTING.md

**Comment by clairecharles** [comment]
Hey, @maxfisher-g  can i work on this?

**Comment by calebbrown** [comment]
Hi @clairecharles, you're more than welcome to work on this.

A new contributors perspective is great for making sure it covers everything it should.

Let us know if you have any questions.

**Comment by maxfisher-g** [comment]
Hi @clairecharles, are you still interested in this issue?
