### ISSUE TITLE
add polyfill and attack tools to sandbox container 

### ISSUE THREAD

**Issue by Alik-Kold** [ossf/package-analysis#587]
Some attackers user various attack tools to execute their attack installing tools such as Wget, Curl and other polyfill, along with attack tools such as nc, tcpdump and other tools commonly used by attacker will allow better visibility over the behavior of the malicious package.

**Comment by maxfisher-g** [comment]
Currently the sandboxes have `curl`, `git`, `wget` and `sudo`. Sounds like we should add `nc` and `tcpdump`. Are there any other specific packages you can think of? 

Also, can you explain more what you mean by polyfill?

**Comment by Alik-Kold** [comment]
polyfill is any tool which might further support the full execution of the attack, In my opinion we should add 

```

powershell
libssl-dev 
wget
curl 
unzip 
zip 
apt-transport-https 
build-essential 
cmake 
protobuf-compiler 
git 
netcat 
telnet 
sudo 
iputils-ping 
iproute2 

and known tools used by attackers: 

tcpdump
tshark
sshpass
auditctl
arp
ifconfig
ipmaddr
iptunnel
mii-tool
nameif
netstat
plipconfig
rarp
route
slattach
trap
kubectl
aws
modprobe
go
insmod
clang
gcc
sql


```

As well as "fooling" the attacker to thinking he landed on a windows host, thus allow him to further execute the attack.

**Comment by maxfisher-g** [comment]
Great ideas! Perhaps we should do #301 first so that we can deduplicate this work

**Comment by maxfisher-g** [comment]
@Alik-Kold when you mentioned `trap`, do you mean the shell command or something else?
