### ISSUE TITLE
Bring Makefile naming in line with criticality score

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/package-analysis#647]
The criticality_score project uses PHONY targets with paths:

e.g:
build/images
build/images/analysis
build/images/scheduler
build/images/python_sandbox

This is useful because the hierarchical naming makes it easy to figure out what the more general case is (i.e. build all would be make build).

**Comment by gliptak** [comment]
would you link the example (approach)?

**Comment by maxfisher-g** [comment]
@gliptak here it is https://github.com/ossf/criticality_score/blob/main/Makefile.

But taking a look at it, it seems like it will be complicated to apply that system to this project. It may not be a good first issue after all :/

**Comment by gliptak** [comment]
starting with #1019

**Comment by maxfisher-g** [comment]
Note: intermediate targets were not implemented in the above PR, e.g. `make build/image` to build all images (but not sandboxes)  and `make sync/sandbox` to sync all sandboxes. These can be added later if desired.
