### ISSUE TITLE
Allow the pubsub implementation to be configurable

### ISSUE THREAD

**Issue by tom--pollard** [ossf/package-analysis#70]
The pubsub library gocloud.dev/pubsub has various ['drivers'](https://pkg.go.dev/gocloud.dev/pubsub?utm_source=godoc#section-directories) (for instance the gcppubsub package) which makes it relatively easy to interact with different 'pubsub' type systems via a common api.

[package-feeds](https://github.com/ossf/package-feeds/blob/main/publisher/kafkapubsub/kafkapubsub.go) has used this extensibility to add support for Kafka, whilst keeping the specific differences behind a generic caller interface.

**Comment by calebbrown** [comment]
I believe this is done.
