### ISSUE TITLE
Is the *.tgz in line 80 of the analyze-tarballs.sh file wrong?

### ISSUE THREAD

**Issue by coffeehb** [ossf/package-analysis#705]
it should be tar.gz not .tgz in analyze-tarballs.sh?

![image](https://user-images.githubusercontent.com/5829776/229769660-5212fd86-25d4-46a7-8c46-3df659022b8b.png)

**Comment by maxfisher-g** [comment]
When I wrote the script, the files I wanted to analyze were `.tgz`, but I agree that `.tar.gz` is probably the most common format. I can add a glob for both formats ;)
