### ISSUE TITLE
Allow the blobstore implementation to be configurable

### ISSUE THREAD

**Issue by tom--pollard** [ossf/package-analysis#71]
The blob library gocloud.dev/blob has various ['drivers'](https://pkg.go.dev/gocloud.dev/blob?utm_source=gopls#section-directories) (for instance the gcsblob package) which makes it relatively easy to interact with different 'blobstore' type backends via a common api.

Utilising this extensibility to allow users to upload results to the supported (s3, azure etc) endpoints via a generic interface may make it easier for wider adoption.

**Comment by naveensrinivasan** [comment]
+1

**Comment by tom--pollard** [comment]
With #83 basic support was added for generic s3 endpoints for the results blobs. However, keeping this issue around for further expansion is probably worth while

**Comment by calebbrown** [comment]
Closing as this appears to be done (as per the docker-compose implementation)
