### ISSUE TITLE
PHP composer installation fails and breaks dynamic analysis dockerfile build

### ISSUE THREAD

**Issue by maxfisher-g** [ossf/package-analysis#781]
PHP composer installation now fails during the dynamic analysis dockerfile build, because installer has been updated, so the checksum is now stale. The commit introducing the change is [this one]( https://github.com/composer/getcomposer.org/commit/70527179915d55b3811bebaec55926afd331091b)

Relevant dockerfile line:
```
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/
```

More robust solutions for automated installation are listed [here](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md). Basically, these are:

1. Downloading the most recent checksum as well as the most recent installer, and comparing the two
2. Pinning a specific version of composer which fixes the checksum until we are ready to update it.

Any thoughts on which option we should choose @calebbrown?

**Comment by maxfisher-g** [comment]
Some possible solutions are listed here: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

**Comment by calebbrown** [comment]
I think #1 is okay. But we probably want to pass the "-version" arg to `composer-setup.php` to ensure a consistent version of composer is installed.
