### ISSUE TITLE
Whether the pushed results are all malicious?

### ISSUE THREAD

**Issue by Wapiti08** [ossf/package-analysis#997]
Dear Authors,

I would like to dive into the details regarding generated results. I am not sure whether only the malicious results are pushed to Bigquery? I did not find any label information regarding that. So I just want to confirm that.

Hope to get the confirmation from you.

Thanks and kind regards,
Newt

**Comment by calebbrown** [comment]
Hi,

Thanks for your interest!

The data in BigQuery contains all results, both for benign packages (the vast majority), and malicious packages.

Also, the dataset is quite large (multiple terabytes) and it may get costly if you run large queries. Please experiment and optimize your queries on smaller subsets of the data.

**Comment by Wapiti08** [comment]
> Hi,
> 
> Thanks for your interest!
> 
> The data in BigQuery contains all results, both for benign packages (the vast majority), and malicious packages.
> 
> Also, the dataset is quite large (multiple terabytes) and it may get costly if you run large queries. Please experiment and optimize your queries on smaller subsets of the data.

Thanks for the answer. By the way, if the Bigquery contains both samples, how to distinguish them? Is there any key information can indicate that?

Hope to get further information on it.

Thanks and kind regards

**Comment by calebbrown** [comment]
The purpose of the Package Analysis project is to collect data about the behaviour and capabilities of a package. This data can be used to find malicious packages, but there is no single simple way to find a malicious package in our data.

You will have to construct queries to find packages that exhibit malicious behaviour and use those results to infer whether or not the package is malicious. See [docs/queries.md](https://github.com/ossf/package-analysis/blob/main/docs/queries.md) for some examples.

If you are interested in malicious packages, see the https://github.com/ossf/malicious-packages repository.

**Comment by Wapiti08** [comment]
> The purpose of the Package Analysis project is to collect data about the behaviour and capabilities of a package. This data can be used to find malicious packages, but there is no single simple way to find a malicious package in our data.
> 
> You will have to construct queries to find packages that exhibit malicious behaviour and use those results to infer whether or not the package is malicious. See [docs/queries.md](https://github.com/ossf/package-analysis/blob/main/docs/queries.md) for some examples.
> 
> If you are interested in malicious packages, see the https://github.com/ossf/malicious-packages repository.

Thanks for the clarification.
